# This configuration uses a webhook to trigger the scaling of the runner deployment.
# Webhooks are confusing so I haven't gotten this to work yet.

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner
spec:
  template:
    spec:
      repository: swils23/actions-experiment
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    name: actions-runner
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
    